// temario-oficial.mjs — Temario de referencia (programa educativo venezolano)
// para 5to grado (primaria) y 1er año (bachillerato / Media General), armado para
// que los niños puedan ADELANTAR materias en vacaciones mientras no tengamos el
// temario EXACTO del colegio (el aula bloquea leer grados donde no estás inscrito).
//
// Cada tema es { t: "título", d: "enfoque" }. El "enfoque" (d) describe subtemas
// concretos, el nivel esperado y los errores típicos; se envía a la IA como contexto
// para que genere contenido ESPECÍFICO y bien calibrado, en vez de genérico. El front
// (pintarGruposProximo) acepta tanto strings (formato viejo) como {t,d}.
//
// Además de las materias oficiales, se agregan materias PUENTE (id 900+, no existen en
// el Moodle del colegio) con lo que más pesa en el salto de grado — sobre todo el
// choque 6to grado → 1er año, que es fuerte: álgebra, negativos, método científico y
// hábitos de estudio. Son de refuerzo, marcadas nombre_corto "PUENTE".
//
// Cuando se consiga un login de un alumno de 5to / 1er año, la captura real del
// Moodle hace UPSERT sobre las filas oficiales (mismo grado + materia_id) y las
// reemplaza por el temario exacto del colegio. Las materias Puente (id 900+) NO se
// pisan porque esos ids no existen en el Moodle.
//
// Los "id" y "nombre_corto" oficiales son los reales del Moodle del colegio (5G: 68-80,
// 1A: 94-108 y 176) para que ese futuro reemplazo calce sin duplicar.

export const TEMARIO = {
  "5to grado": [
    { id: 72, materia: "Matemáticas", nombre_corto: "MATEMÁTICAS 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Números naturales hasta millones y millardos: lectura, escritura y valor posicional",
          d: "Leer y escribir números grandes con soltura; identificar el valor posicional de cada cifra (unidades, decenas, centenas, unidad de mil, millón, millardo). Descomponer un número (ej. 3.482.019 = 3 millones + 482 mil + 19). Error típico: perderse con los ceros intermedios y con la separación por clases. Practicar con cifras de la vida real (habitantes, distancias, bolívares)." },
        { t: "Orden y comparación de números naturales",
          d: "Comparar y ordenar naturales grandes usando >, < e =; ubicar en la recta numérica; redondear a la decena, centena y unidad de mil más cercana. Error típico: comparar por cantidad de cifras sin alinear el valor posicional. Incluir problemas de 'el mayor/menor' y de ordenar listas." },
        { t: "Adición y sustracción de números naturales",
          d: "Sumar y restar con reagrupación (llevar y pedir prestado), varias cifras. Propiedad de la resta como inversa de la suma; comprobar restas sumando. Problemas de enunciado de uno y dos pasos con dinero y cantidades. Error típico: fallar el 'pedir prestado' con ceros seguidos." },
        { t: "Multiplicación de números naturales",
          d: "Multiplicar por una, dos y tres cifras con acarreo; el rol del cero al multiplicar por decenas/centenas. Estimar el resultado antes de calcular. Problemas de proporcionalidad simple (precio por cantidad). Error típico: no correr el segundo renglón al multiplicar por decenas." },
        { t: "División de números naturales (una y dos cifras)",
          d: "División larga por una y dos cifras; identificar dividendo, divisor, cociente y resto; comprobar con divisor×cociente+resto=dividendo. Problemas de reparto y de agrupación. Error típico: bajar mal la siguiente cifra o olvidar el cero en el cociente." },
        { t: "Propiedades de la adición y la multiplicación",
          d: "Conmutativa, asociativa, elemento neutro (0 y 1) y distributiva de la multiplicación respecto a la suma. Usar las propiedades para calcular más fácil (ej. 25×12 = 25×10 + 25×2). Error típico: creer que la resta y la división también son conmutativas." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Múltiplos y divisores; criterios de divisibilidad",
          d: "Hallar múltiplos y divisores de un número; criterios de divisibilidad por 2, 3, 5, 9 y 10. Distinguir múltiplo (resultado de multiplicar) de divisor (divide exacto). Error típico: confundir múltiplo con divisor. Practicar decidiendo rápido si un número es divisible sin dividir." },
        { t: "Números primos y compuestos",
          d: "Reconocer primos y compuestos; descomponer en factores primos (factorización) usando el árbol o divisiones sucesivas. La criba de Eratóstenes para hallar primos hasta 100. Error típico: olvidar que 1 no es primo y que 2 es el único primo par." },
        { t: "Mínimo común múltiplo y máximo común divisor",
          d: "Calcular m.c.m. y M.C.D. por factorización en primos; cuándo se usa cada uno (m.c.m. para 'volver a coincidir', M.C.D. para 'repartir en grupos iguales'). Error típico: mezclar los procedimientos. Incluir problemas verbales (autobuses que coinciden, repartir sin que sobre)." },
        { t: "Fracciones: representación, comparación y equivalencia",
          d: "Fracción como parte de un todo y de una cantidad; numerador y denominador; fracciones equivalentes (amplificar/simplificar); comparar con igual y con distinto denominador. Error típico: creer que una fracción es mayor solo porque el denominador es mayor." },
        { t: "Suma y resta de fracciones",
          d: "Sumar y restar con igual denominador y con distinto denominador (usando m.c.m. para el común denominador); simplificar el resultado. Fracciones propias e impropias, número mixto. Error típico: sumar numeradores Y denominadores. Ejemplos con medidas y recetas." },
        { t: "Multiplicación y división de fracciones",
          d: "Multiplicar fracción por fracción y por entero; dividir invirtiendo la segunda (multiplicar por el recíproco); simplificar en cruz antes de operar. Error típico: aplicar el común denominador (de la suma) a la multiplicación. Ejemplos de 'la mitad de tres cuartos'." },
        { t: "Números decimales: lectura, orden y operaciones",
          d: "Décimas, centésimas y milésimas; leer y escribir decimales; compararlos alineando la coma; sumar, restar y multiplicar decimales; relación fracción decimal. Error típico: no alinear la coma al sumar/restar y contar mal los decimales al multiplicar." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Proporcionalidad: regla de tres simple directa e inversa",
          d: "Reconocer magnitudes directamente proporcionales (más↔más) vs inversamente (más↔menos); plantear y resolver regla de tres simple. Error típico: usar directa cuando es inversa (ej. más obreros → menos tiempo). Practicar identificando primero el tipo antes de calcular." },
        { t: "Porcentaje y su cálculo",
          d: "Porcentaje como fracción de 100; calcular el % de una cantidad; descuentos y aumentos sencillos; pasar de fracción/decimal a porcentaje. Error típico: no relacionar 50% con 1/2 y 25% con 1/4. Ejemplos con rebajas y notas." },
        { t: "Medidas de longitud, masa, capacidad y tiempo",
          d: "Unidades del sistema métrico (km, m, cm, mm; kg, g; L, mL) y conversiones multiplicando/dividiendo por 10, 100, 1000; unidades de tiempo y su conversión. Error típico: convertir en el sentido equivocado. Problemas de la vida diaria." },
        { t: "Perímetro y área de figuras planas",
          d: "Perímetro como suma de lados; área del cuadrado, rectángulo y triángulo con sus fórmulas; diferenciar claramente perímetro (borde, en unidades) de área (superficie, en unidades²). Error típico: confundir perímetro con área y olvidar el ÷2 del triángulo." },
        { t: "Ángulos y su medición",
          d: "Ángulo recto, agudo, obtuso y llano; medir y dibujar con transportador; ángulos en figuras. Error típico: leer el transportador por la escala equivocada. Reconocer ángulos en objetos cotidianos." },
        { t: "Estadística: tablas, gráficos de barras y promedio",
          d: "Organizar datos en tablas de frecuencia; leer y construir gráficos de barras y pictogramas; calcular el promedio (media aritmética). Error típico: al promediar, sumar bien pero dividir entre el número equivocado de datos. Interpretar qué dice el gráfico." },
      ]},
    ]},
    { id: 79, materia: "Lógica Matemática", nombre_corto: "LÓGICA MAT 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Secuencias y patrones numéricos",
          d: "Descubrir la regla de una secuencia (sumar, restar, multiplicar un valor fijo, o alternar) y continuarla; secuencias crecientes y decrecientes. Error típico: mirar solo el primer salto sin verificar que la regla se mantiene. Pedir que expliquen la regla con palabras." },
        { t: "Series de figuras",
          d: "Patrones visuales: forma, color, tamaño, rotación y cantidad que cambian con una regla; predecir la figura siguiente. Error típico: fijarse en un solo atributo cuando cambian dos a la vez." },
        { t: "Razonamiento con operaciones",
          d: "Elegir la operación correcta según el enunciado; operaciones combinadas respetando el orden (primero × y ÷, luego + y −); completar el número que falta. Error típico: resolver de izquierda a derecha ignorando la jerarquía." },
        { t: "Problemas de sumas y restas con enunciado",
          d: "Traducir un problema verbal a una operación; problemas de comparación ('cuántos más/menos') y de cambio; identificar el dato que sobra. Error típico: sumar cuando la palabra clave engaña (no siempre 'más' es sumar)." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Problemas de multiplicación y división",
          d: "Problemas de reparto, agrupación y proporcionalidad; problemas de dos pasos (multiplicar y luego restar, etc.). Error típico: no distinguir 'repartir en partes iguales' (división) de 'cuántas veces cabe'. Comprobar la razonabilidad del resultado." },
        { t: "Acertijos numéricos",
          d: "Adivinar un número a partir de pistas ('soy par, mayor que 20, mis cifras suman 7'); descartar posibilidades con lógica. Error típico: no usar TODAS las pistas para verificar la única respuesta. Enseñar a probar y descartar." },
        { t: "Cuadrados mágicos",
          d: "Completar cuadrados donde filas, columnas y diagonales suman lo mismo; deducir la constante mágica. Error típico: completar sin comprobar las tres direcciones. Empezar por la fila/columna con más datos." },
        { t: "Razonamiento lógico: verdadero/falso y deducción",
          d: "Evaluar si una afirmación es verdadera o falsa; deducir de premisas sencillas ('si todos los gatos... y Michi es gato...'); detectar contradicciones. Error típico: sacar conclusiones que las pistas no garantizan." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Problemas de proporcionalidad y regla de tres",
          d: "Problemas verbales de proporcionalidad directa e inversa (recetas, velocidad, precios); reconocer el tipo antes de calcular. Error típico: aplicar regla de tres directa a una situación inversa. Estimar si la respuesta debe ser mayor o menor." },
        { t: "Conteo y combinaciones sencillas",
          d: "Contar combinaciones y arreglos de forma organizada (diagramas de árbol, tablas); principio de multiplicación ('3 camisas y 2 pantalones → 6 conjuntos'). Error típico: contar por tanteo desordenado y repetir o saltar casos." },
        { t: "Problemas de dos pasos",
          d: "Problemas que exigen dos operaciones encadenadas; identificar el resultado intermedio antes del final. Error típico: quedarse en el primer paso y dar ese como respuesta. Enseñar a subrayar qué se pregunta al final." },
        { t: "Retos de ingenio con geometría",
          d: "Contar figuras dentro de una figura, cortar y armar, caminos posibles, simetrías; razonamiento espacial. Error típico: contar solo las figuras evidentes y olvidar las compuestas. Fomentar dibujar y marcar." },
      ]},
    ]},
    { id: 71, materia: "Lenguaje", nombre_corto: "LENGUAJE 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Comprensión lectora",
          d: "Idea principal e ideas secundarias; inferir lo que no está dicho; secuencia de hechos; significado por contexto. Error típico: responder con lo primero que aparece sin releer. Trabajar preguntas literales y de inferencia sobre un texto corto." },
        { t: "El sustantivo y el adjetivo",
          d: "Sustantivo (común/propio, concreto/abstracto, individual/colectivo) y adjetivo calificativo con su concordancia en género y número. Error típico: confundir adjetivo con sustantivo. Reconocerlos dentro de oraciones." },
        { t: "El artículo",
          d: "Artículos definidos e indefinidos; concordancia con el sustantivo; contracciones al y del. Error típico: fallar la concordancia (el/la, un/una) y no reconocer las contracciones." },
        { t: "Sílaba tónica y átona; acentuación",
          d: "Separar en sílabas, hallar la sílaba tónica; clasificar en agudas, graves y esdrújulas; reglas generales de acentuación. Error típico: marcar la tilde por 'cómo suena' sin aplicar la regla. Muchos ejemplos de cada tipo." },
        { t: "Signos de puntuación: punto y coma",
          d: "Uso del punto (seguido, aparte, final), la coma (enumeración, vocativo, aclaración) y el punto y coma. Error típico: comas donde no van y textos sin puntos. Leer en voz alta para 'oír' las pausas." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El verbo y sus tiempos: presente, pasado y futuro",
          d: "Reconocer el verbo como acción; conjugar en presente, pasado y futuro; persona y número. Error típico: no mantener el mismo tiempo dentro de un texto. Practicar transformando oraciones de un tiempo a otro." },
        { t: "El pronombre",
          d: "Pronombres personales (yo, tú, él…) y su uso para no repetir el sustantivo. Error típico: repetir el nombre en vez de usar pronombre, o usar el pronombre equivocado. Reescribir textos evitando repeticiones." },
        { t: "Sinónimos y antónimos",
          d: "Palabras de significado parecido (sinónimos) y opuesto (antónimos); enriquecer el vocabulario y evitar repetir. Error típico: dar como sinónimo una palabra que no encaja en el contexto." },
        { t: "La oración: sujeto y predicado",
          d: "Identificar sujeto (de quién se habla) y predicado (qué se dice); núcleo del sujeto; sujeto tácito. Error típico: confundir el sujeto con la primera palabra de la oración. Separar oraciones en sus dos partes." },
        { t: "Uso de b/v y de c/s/z",
          d: "Reglas ortográficas frecuentes de b/v y de c/s/z; palabras de uso común que suelen fallar. Error típico: escribir 'de oído'. Trabajar con dictados cortos y familias de palabras." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "El párrafo y el texto",
          d: "El párrafo como unidad con una idea; oración principal y de apoyo; conectores básicos; organizar ideas antes de escribir. Error típico: párrafos de una sola oración larga o sin idea central." },
        { t: "Tipos de textos: narrativo, descriptivo e instructivo",
          d: "Distinguir para qué sirve cada tipo y su estructura (narrar hechos, describir cómo es algo, dar instrucciones en orden). Error típico: mezclar tipos sin darse cuenta. Reconocer el tipo leyendo ejemplos." },
        { t: "La carta y el correo",
          d: "Partes de la carta (saludo, cuerpo, despedida) y del correo electrónico; lenguaje formal vs informal según el destinatario. Error típico: olvidar el saludo/despedida o mezclar registros." },
        { t: "El cuento y la leyenda",
          d: "Estructura del cuento (inicio, nudo, desenlace); personajes y ambiente; qué distingue la leyenda (explica algo, base cultural). Error típico: contar sin desenlace claro. Leer una leyenda venezolana." },
        { t: "Producción de textos propios",
          d: "Planificar (lluvia de ideas), escribir borrador, revisar y corregir; coherencia y cohesión; ortografía en la revisión. Error típico: entregar el primer borrador sin releer. Enseñar el ciclo escribir-revisar." },
      ]},
    ]},
    { id: 68, materia: "Ciencias Naturales", nombre_corto: "CS NATURALES 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La célula y los seres vivos",
          d: "La célula como unidad de la vida; partes básicas (membrana, citoplasma, núcleo); célula animal vs vegetal (pared y cloroplastos). Error típico: creer que las plantas no tienen células. Relacionar con lo vivo vs no vivo." },
        { t: "Clasificación de los seres vivos",
          d: "Idea de los grandes grupos/reinos; criterios para clasificar (cómo se nutren, si se mueven); ejemplos de cada grupo. Error típico: clasificar por tamaño o apariencia en vez de por características. " },
        { t: "Vertebrados e invertebrados",
          d: "Presencia o no de columna vertebral; los cinco grupos de vertebrados (mamíferos, aves, reptiles, anfibios, peces) y sus rasgos; ejemplos de invertebrados. Error típico: llamar 'insecto' a todo invertebrado." },
        { t: "Las plantas y su nutrición: la fotosíntesis",
          d: "Cómo la planta fabrica su alimento con luz, agua y CO₂, y libera oxígeno; partes de la planta y su función. Error típico: pensar que la planta 'come' del suelo. Explicar el papel de la luz solar." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El cuerpo humano: sistema digestivo",
          d: "Recorrido del alimento (boca, esófago, estómago, intestinos) y para qué sirve digerir; hábitos saludables. Error típico: desordenar los órganos del recorrido." },
        { t: "Sistema respiratorio",
          d: "Cómo entra y sale el aire (nariz, tráquea, pulmones) y el intercambio de oxígeno; cuidado de los pulmones. Error típico: confundir respirar con solo 'tomar aire'." },
        { t: "Sistema circulatorio",
          d: "El corazón y la sangre que reparte oxígeno y nutrientes; venas y arterias en idea sencilla. Error típico: creer que la sangre solo lleva oxígeno. Relacionar con el pulso." },
        { t: "Alimentación y salud",
          d: "Grupos de alimentos y dieta balanceada; importancia del agua y del ejercicio; higiene. Error típico: clasificar alimentos como 'buenos/malos' sin matiz de cantidad y variedad." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "La materia y sus estados",
          d: "Sólido, líquido y gaseoso y sus características; cambios de estado (fusión, evaporación, condensación, solidificación) por calor/frío. Error típico: confundir el nombre de cada cambio." },
        { t: "Mezclas y métodos de separación",
          d: "Mezclas homogéneas y heterogéneas; separar por filtración, decantación, evaporación, imantación según el caso. Error típico: elegir el método que no corresponde a la mezcla." },
        { t: "La energía y sus formas",
          d: "Formas de energía (luz, calor, sonido, movimiento, eléctrica) y transformaciones; fuentes renovables y no renovables. Error típico: creer que la energía se 'gasta' y desaparece." },
        { t: "El agua y su ciclo",
          d: "Etapas del ciclo (evaporación, condensación, precipitación); importancia y cuidado del agua. Error típico: saltarse la condensación al explicar el ciclo." },
        { t: "El suelo y su cuidado",
          d: "Tipos y capas del suelo, para qué sirve, cómo se contamina y cómo cuidarlo. Error típico: no relacionar el suelo con la vida de plantas y personas." },
      ]},
    ]},
    { id: 69, materia: "Ciencias Sociales", nombre_corto: "CS SOCIALES 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La Tierra: continentes y océanos",
          d: "Nombrar y ubicar los continentes y océanos; usar el globo/mapa; puntos cardinales. Error típico: confundir continente con país u océano con mar." },
        { t: "Venezuela: ubicación y límites",
          d: "Ubicación de Venezuela en América y el mundo; países limítrofes y mar Caribe. Error típico: no ubicar los límites por punto cardinal." },
        { t: "El relieve de Venezuela",
          d: "Formas del relieve (llanuras, montañas, mesetas); la cordillera de los Andes, el Ávila, los Llanos, Guayana. Error típico: mezclar relieve con clima o con región política." },
        { t: "Regiones naturales de Venezuela",
          d: "Las regiones naturales y qué caracteriza a cada una (clima, vegetación, actividades). Error típico: no asociar cada región con su ubicación." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Población de Venezuela",
          d: "Dónde y cómo vive la gente; población urbana y rural; diversidad. Error típico: confundir población con territorio." },
        { t: "Estados y capitales",
          d: "Los estados de Venezuela y sus capitales; ubicarlos en el mapa. Error típico: mezclar estado con capital. Memorizar por regiones ayuda." },
        { t: "Actividades económicas",
          d: "Sector primario, secundario y terciario con ejemplos venezolanos (petróleo, agricultura, comercio). Error típico: no clasificar bien una actividad por sector." },
        { t: "Recursos naturales",
          d: "Recursos renovables y no renovables; el petróleo; uso responsable. Error típico: creer que todos los recursos se agotan igual." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "La independencia de Venezuela",
          d: "Causas y hechos clave del proceso de independencia; el 19 de abril y el 5 de julio. Error típico: confundir fechas y su significado." },
        { t: "Simón Bolívar y los próceres",
          d: "Rol de Bolívar y otros próceres (Miranda, Sucre); ideas de libertad. Error típico: atribuir todo a una sola figura." },
        { t: "Símbolos patrios",
          d: "Bandera, escudo e himno: significado de sus elementos y respeto. Error típico: no recordar el significado de los colores/elementos." },
        { t: "Deberes y derechos del ciudadano",
          d: "Derechos y deberes básicos; convivencia y respeto a las normas. Error típico: reclamar derechos sin reconocer deberes." },
      ]},
    ]},
    { id: 75, materia: "Inglés", nombre_corto: "INGLÉS 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "The alphabet and greetings",
          d: "Deletrear (spelling), saludos y despedidas, preguntar el nombre. Error típico: pronunciar las letras como en español. Practicar deletreando su propio nombre." },
        { t: "Numbers and colors",
          d: "Números 1–100 y colores; contar objetos y describir por color. Error típico: confundir thirteen/thirty y colores parecidos." },
        { t: "Personal pronouns",
          d: "I, you, he, she, it, we, they y su uso. Error típico: usar he/she para objetos o confundir géneros." },
        { t: "Verb to be",
          d: "am/is/are en afirmativo, negativo e interrogativo; presentaciones. Error típico: 'I is', y omitir el verbo to be." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Family members",
          d: "Vocabulario de la familia y posesivos básicos (my, your). Error típico: confundir parientes (aunt/uncle)." },
        { t: "Parts of the body",
          d: "Partes del cuerpo; describir con have/has. Error típico: plural irregular (foot/feet)." },
        { t: "Animals",
          d: "Animales comunes y descripción sencilla (it is / it has). Error típico: pronunciación y singular/plural." },
        { t: "Present simple: daily routines",
          d: "Rutinas diarias con present simple; la -s de tercera persona. Error típico: olvidar la -s en he/she." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Food and drinks",
          d: "Comidas y bebidas; like/don't like; contables e incontables (a/an, some). Error típico: 'a water'." },
        { t: "The house and rooms",
          d: "Cuartos y muebles; there is/there are. Error típico: there is con plural." },
        { t: "Prepositions of place",
          d: "in, on, under, next to; ubicar objetos. Error típico: confundir in/on." },
        { t: "Telling the time",
          d: "Decir la hora (o'clock, half past); rutinas con horas. Error típico: leer la hora como en español." },
      ]},
    ]},
    { id: 76, materia: "Informática", nombre_corto: "INFORMÁTICA 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Partes de la computadora", d: "Componentes básicos (monitor, CPU, teclado, mouse) y su función; dispositivos de entrada y salida. Error típico: confundir entrada con salida." },
        { t: "Hardware y software", d: "Diferencia entre lo físico (hardware) y los programas (software); ejemplos de cada uno. Error típico: llamar hardware a un programa." },
        { t: "Uso del teclado y el mouse", d: "Teclas principales, clic/doble clic/arrastrar; postura y cuidado del equipo. Error típico: no distinguir clic de doble clic." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El sistema operativo", d: "Qué es y para qué sirve; escritorio, ventanas e íconos. Error típico: confundir el sistema operativo con un programa cualquiera." },
        { t: "Carpetas y archivos", d: "Crear, nombrar, guardar y organizar; rutas básicas. Error típico: guardar sin saber dónde y perder el archivo." },
        { t: "El procesador de texto", d: "Escribir, dar formato (negrita, tamaño), guardar e imprimir. Error típico: no guardar antes de cerrar." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Internet y navegación segura", d: "Qué es internet y el navegador; reglas de seguridad y privacidad para niños. Error típico: dar datos personales en línea." },
        { t: "El correo electrónico", d: "Partes de una dirección y de un correo; enviar/recibir con respeto. Error típico: confundir 'para' con 'asunto'." },
        { t: "Presentaciones básicas", d: "Crear diapositivas con texto e imágenes; ideas por diapositiva. Error típico: llenar la diapositiva de texto." },
      ]},
    ]},
    { id: 74, materia: "Liderazgo Comunicacional", nombre_corto: "LID COMUNIC 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La comunicación", d: "Emisor, mensaje y receptor; comunicación verbal y no verbal. Error típico: creer que solo se comunica con palabras." },
        { t: "Escucha activa", d: "Prestar atención, no interrumpir, preguntar para entender. Error típico: pensar la respuesta en vez de escuchar." },
        { t: "Expresión oral", d: "Hablar claro, con volumen y postura; ordenar las ideas. Error típico: hablar muy rápido o bajito." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Trabajo en equipo", d: "Roles, colaboración y metas comunes. Error típico: que uno haga todo el trabajo." },
        { t: "Resolución de conflictos", d: "Dialogar, ceder y buscar acuerdos. Error típico: imponer en vez de negociar." },
        { t: "Respeto y empatía", d: "Ponerse en el lugar del otro; respetar diferencias. Error típico: confundir empatía con estar de acuerdo en todo." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Hablar en público", d: "Preparar, respirar y mirar al público; vencer los nervios. Error típico: leer todo sin mirar." },
        { t: "Liderazgo positivo", d: "Dar el ejemplo, motivar, incluir. Error típico: confundir liderar con mandar." },
        { t: "Proyectos comunitarios", d: "Detectar una necesidad y organizar una acción sencilla. Error típico: planear sin repartir tareas." },
      ]},
    ]},
    { id: 70, materia: "Educación Estética", nombre_corto: "EDUC ESTÉTICA 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "El dibujo y la línea", d: "Tipos de línea y trazo; proporción básica. Error típico: apretar mucho el lápiz." },
        { t: "Colores primarios y secundarios", d: "Mezclas de color y el círculo cromático. Error típico: no saber qué colores forman los secundarios." },
        { t: "Formas y figuras", d: "Formas geométricas y orgánicas en composiciones. Error típico: no organizar el espacio." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "La pintura", d: "Técnicas con témpera/acuarela; luz y sombra básica. Error típico: mezclar en exceso y ensuciar el color." },
        { t: "Manualidades", d: "Crear con material reciclado; motricidad fina. Error típico: no planificar los pasos." },
        { t: "El collage", d: "Componer con recortes y texturas. Error típico: pegar sin composición." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Apreciación artística", d: "Observar y comentar obras; gustos y emociones. Error típico: juzgar solo 'bonito/feo'." },
        { t: "Artistas venezolanos", d: "Reconocer artistas y obras venezolanas (ej. Reverón, Soto). Error típico: no ubicarlos culturalmente." },
        { t: "Proyecto artístico", d: "Idear y crear una obra propia con una técnica elegida. Error típico: empezar sin idea." },
      ]},
    ]},
    { id: 80, materia: "Música", nombre_corto: "MÚSICA 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "El sonido y sus cualidades", d: "Altura, duración, intensidad y timbre. Error típico: confundir volumen con altura (grave/agudo)." },
        { t: "Las notas musicales", d: "Do re mi fa sol la si; su orden. Error típico: desordenar la escala." },
        { t: "El ritmo", d: "Pulso y ritmo; palmas y percusión corporal. Error típico: perder el pulso constante." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Instrumentos musicales", d: "Familias (cuerda, viento, percusión) con ejemplos. Error típico: clasificar mal un instrumento." },
        { t: "La melodía", d: "Melodía vs acompañamiento; cantar afinado. Error típico: confundir melodía con ritmo." },
        { t: "Canciones tradicionales venezolanas", d: "Reconocer canciones y su origen. Error típico: no ubicar la región musical." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "El pentagrama", d: "Líneas, espacios y clave de sol; ubicar notas. Error típico: contar líneas/espacios al revés." },
        { t: "Interpretación grupal", d: "Tocar/cantar juntos siguiendo un pulso común. Error típico: adelantarse al grupo." },
        { t: "Géneros musicales venezolanos", d: "Joropo, gaita y otros; sus rasgos. Error típico: confundir géneros." },
      ]},
    ]},
    { id: 78, materia: "Religión", nombre_corto: "RELIGIÓN 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La creación", d: "Relato de la creación y cuidado de lo creado. Error típico: leerlo sin el mensaje de cuidado." },
        { t: "Valores cristianos", d: "Amor, respeto, honestidad y solidaridad en la vida diaria. Error típico: enumerar valores sin ejemplos." },
        { t: "La familia", d: "La familia como comunidad de amor y valores. Error típico: idea única de familia." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Historias de la Biblia", d: "Relatos clave y su enseñanza. Error típico: quedarse en la anécdota sin el mensaje." },
        { t: "Jesús y sus enseñanzas", d: "Vida y mensaje de Jesús; el amor al prójimo. Error típico: solo hechos, sin enseñanza." },
        { t: "La solidaridad", d: "Ayudar a los demás con gestos concretos. Error típico: confundir solidaridad con lástima." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Las parábolas", d: "Qué es una parábola y su enseñanza (ej. buen samaritano). Error típico: leerla literal sin el mensaje." },
        { t: "Fiestas religiosas", d: "Sentido de las principales fiestas. Error típico: solo lo festivo, sin el significado." },
        { t: "El servicio a los demás", d: "Servir en la escuela y la comunidad. Error típico: servir esperando premio." },
      ]},
    ]},
    { id: 77, materia: "Robótica", nombre_corto: "ROBÓTICA 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "¿Qué es un robot?", d: "Idea de robot y ejemplos reales; qué los hace 'automáticos'. Error típico: llamar robot a cualquier máquina." },
        { t: "Partes de un robot", d: "Sensor, control y actuador en idea sencilla. Error típico: no distinguir sensor de actuador." },
        { t: "Máquinas simples", d: "Palanca, polea, rueda y plano inclinado; para qué sirven. Error típico: no reconocerlas en objetos." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Sensores y actuadores", d: "El sensor 'percibe' y el actuador 'hace'; ejemplos. Error típico: intercambiar sus roles." },
        { t: "Secuencias y algoritmos", d: "Instrucciones en orden para lograr una tarea. Error típico: pasos desordenados o incompletos." },
        { t: "Programación por bloques", d: "Encajar bloques para dar órdenes; probar y corregir. Error típico: no probar paso a paso." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Armado de un robot básico", d: "Montar una estructura simple con partes. Error típico: montar sin plan." },
        { t: "Programación de movimientos", d: "Ordenar avances, giros y pausas. Error típico: no medir tiempos/distancias." },
        { t: "Proyecto de robótica", d: "Resolver un reto pequeño integrando todo. Error típico: no dividir el reto en pasos." },
      ]},
    ]},
    { id: 73, materia: "Educación Física", nombre_corto: "EDUC FÍSICA 5G", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Calentamiento y estiramiento", d: "Para qué sirven y cómo hacerlos antes/después. Error típico: saltarse el calentamiento." },
        { t: "Capacidades físicas", d: "Fuerza, velocidad, resistencia y flexibilidad. Error típico: confundirlas entre sí." },
        { t: "Juegos pre-deportivos", d: "Juegos que preparan para deportes; reglas simples. Error típico: no respetar turnos/reglas." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Voleibol y baloncesto", d: "Gestos básicos y reglas iniciales. Error típico: dobles/pasos por desconocer la regla." },
        { t: "Coordinación y equilibrio", d: "Ejercicios de coordinación óculo-manual y equilibrio. Error típico: hacerlos con prisa." },
        { t: "Atletismo básico", d: "Correr, saltar y lanzar con técnica sencilla. Error típico: mala respiración al correr." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Fútbol y kickingball", d: "Reglas y fundamentos básicos. Error típico: desconocer faltas básicas." },
        { t: "Hábitos saludables", d: "Hidratación, descanso y actividad regular. Error típico: no hidratarse." },
        { t: "Juegos tradicionales", d: "Juegos venezolanos y su valor cultural. Error típico: no conocer las reglas tradicionales." },
      ]},
    ]},
    { id: 970, materia: "Puente a 5to grado", nombre_corto: "PUENTE 5G", grupos: [
      { lapso: "Refuerzo para llegar firme", temas: [
        { t: "Dominar las tablas de multiplicar (fluidez)",
          d: "Recordar las tablas del 1 al 12 con rapidez y sin contar con los dedos; esto sostiene TODO lo que viene (fracciones, división larga, m.c.m.). Trucos por patrones (×9, ×5, cuadrados). Error típico: fallar las del 6, 7 y 8. Practicar con retos cronometrados suaves." },
        { t: "Problemas de varios pasos: entender antes de calcular",
          d: "Leer un problema, subrayar datos y la pregunta, decidir las operaciones EN ORDEN y comprobar si la respuesta tiene sentido. Es la base del razonamiento de 5to. Error típico: operar los números sin entender qué se pide." },
        { t: "Fracciones y decimales en la vida real",
          d: "Reforzar fracciones (mitad, tercio, cuarto), pasarlas a decimales y usarlas en dinero, recetas y medidas; equivalencias 1/2=0,5=50%. Error típico: no conectar fracción, decimal y porcentaje como lo mismo escrito distinto." },
        { t: "Cálculo mental y estimación",
          d: "Estimar resultados antes de calcular para detectar errores; redondear para sumar/restar rápido; descomponer números. Error típico: dar por buena una respuesta absurda por no estimar." },
        { t: "Escribir un texto ordenado (borrador y revisión)",
          d: "Planear ideas, escribir un párrafo con inicio-desarrollo-cierre y RELEER para corregir ortografía y puntuación. Prepara la producción escrita de 5to. Error típico: entregar sin releer." },
      ]},
    ]},
  ],

  "1er año": [
    { id: 103, materia: "Matemáticas", nombre_corto: "MATEMÁTICAS 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Conjuntos numéricos: N, Z y Q",
          d: "Distinguir naturales (N), enteros (Z, con negativos) y racionales (Q, fracciones/decimales); cómo cada conjunto amplía al anterior; ubicar en la recta. CLAVE en el salto a bachillerato: aparecen los negativos. Error típico: creer que 'número' es solo lo positivo y no ubicar racionales entre enteros." },
        { t: "Números naturales: operaciones y propiedades",
          d: "Repaso firme de operaciones en N y jerarquía de operaciones con paréntesis (PEMDAS: primero paréntesis, luego potencias, ×/÷, +/−). Error típico: resolver de izquierda a derecha ignorando la jerarquía. Base para el álgebra." },
        { t: "Potenciación y radicación en N",
          d: "Potencia como multiplicación repetida (base y exponente); cuadrados y cubos; raíz cuadrada exacta como operación inversa; leyes básicas de potencias (misma base). Error típico: multiplicar base×exponente en vez de potenciar." },
        { t: "Números enteros: operaciones",
          d: "Sumar, restar, multiplicar y dividir enteros CON SIGNO; regla de signos (− por − = +); suma en la recta numérica. EL tema donde más se traba el que viene de 6to. Error típico: 'menos por menos' y restar un negativo (a−(−b)=a+b)." },
        { t: "Valor absoluto y orden en Z",
          d: "Valor absoluto como distancia al cero (siempre positivo); comparar enteros (−5 < −2); opuesto de un número. Error típico: creer que −5 es mayor que −2 porque 5>2." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Números racionales: fracciones y decimales",
          d: "Fracciones y decimales como racionales; convertir de fracción a decimal y viceversa; decimal periódico; fracciones negativas. Error típico: no manejar el signo en fracciones y confundir el orden de racionales." },
        { t: "Operaciones con números racionales",
          d: "Sumar, restar, multiplicar y dividir fracciones (con común denominador y con signo); operaciones combinadas con jerarquía. Error típico: aplicar común denominador a la multiplicación y perder el signo." },
        { t: "Razones y proporciones",
          d: "Razón como comparación (a:b), proporción como igualdad de razones; propiedad fundamental (producto cruzado); hallar el término desconocido. Error típico: cruzar mal los productos." },
        { t: "Regla de tres y porcentaje",
          d: "Regla de tres simple directa e inversa y compuesta sencilla; porcentaje como razón a 100; aumentos, descuentos e interés simple básico. Error típico: no distinguir directa de inversa y calcular el % sobre la base equivocada." },
        { t: "Expresiones algebraicas: términos y valor numérico",
          d: "La LETRA como número desconocido; término, coeficiente, parte literal; términos semejantes y su reducción; evaluar (valor numérico) sustituyendo la letra. PRIMER contacto real con álgebra: el corazón del salto a bachillerato. Error típico: sumar términos no semejantes (3x+2 ≠ 5x)." },
        { t: "Ecuaciones de primer grado",
          d: "Resolver ax+b=c despejando paso a paso; 'lo que pasa al otro lado cambia de operación'; comprobar sustituyendo; plantear ecuaciones desde un enunciado. Error típico: cambiar mal el signo/operación al despejar y no comprobar." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Ángulos y su clasificación",
          d: "Agudo, recto, obtuso, llano; ángulos complementarios (suman 90°) y suplementarios (suman 180°); opuestos por el vértice. Error típico: confundir complementario con suplementario." },
        { t: "Triángulos y sus propiedades",
          d: "Clasificar por lados y por ángulos; la suma de ángulos internos = 180°; desigualdad triangular. Error típico: proponer triángulos imposibles (lados que no cierran) u olvidar el 180°." },
        { t: "Cuadriláteros y polígonos",
          d: "Tipos de cuadriláteros (cuadrado, rectángulo, rombo, trapecio) y sus propiedades; suma de ángulos de un polígono. Error típico: confundir rombo con cuadrado y no distinguir propiedades." },
        { t: "Perímetro y área",
          d: "Perímetro y área de triángulo, cuadrado, rectángulo, paralelogramo y trapecio con sus fórmulas; unidades (u vs u²). Error típico: usar la fórmula equivocada y mezclar unidades de perímetro y área." },
        { t: "Circunferencia y círculo",
          d: "Diferencia entre circunferencia (línea) y círculo (superficie); radio, diámetro; longitud (2πr) y área (πr²) con π≈3,14. Error típico: usar el diámetro donde va el radio." },
        { t: "Estadística: frecuencia, media, mediana y moda",
          d: "Tabla de frecuencias; calcular media (promedio), mediana (valor central ordenado) y moda (más repetido); interpretar gráficos. Error típico: sacar la mediana sin ordenar los datos y confundir media con moda." },
      ]},
    ]},
    { id: 102, materia: "Lógica Matemática", nombre_corto: "LÓGICA MAT 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Proposiciones y valor de verdad",
          d: "Qué es una proposición (afirmación V o F) y qué no lo es; asignar valor de verdad. Error típico: tomar preguntas u órdenes como proposiciones." },
        { t: "Conectivos lógicos: y, o, no",
          d: "Conjunción (y), disyunción (o) y negación (no); cómo cambian el valor de verdad. Error típico: confundir el 'o' inclusivo con el exclusivo." },
        { t: "Tablas de verdad",
          d: "Construir tablas para ∧, ∨ y ¬ y combinaciones simples; leer todos los casos posibles. Error típico: olvidar combinaciones de V/F o equivocar el resultado de la disyunción." },
        { t: "Razonamiento deductivo",
          d: "Sacar conclusiones válidas de premisas; distinguir conclusión válida de invento. Error típico: concluir de más ('todos... entonces este específico...' sin base)." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Secuencias y patrones",
          d: "Hallar la regla (aritmética o combinada) y el término siguiente/general de una secuencia. Error típico: mirar solo el primer salto." },
        { t: "Problemas de razonamiento numérico",
          d: "Traducir enunciados a operaciones/ecuaciones sencillas; problemas de edades, mezclas, monedas. Error típico: plantear mal la relación entre datos." },
        { t: "Conjuntos: unión, intersección y diferencia",
          d: "Operaciones entre conjuntos y su significado; pertenencia y subconjunto. Error típico: confundir unión con intersección." },
        { t: "Diagramas de Venn",
          d: "Representar conjuntos y resolver problemas de 'cuántos hacen A y B'; regiones. Error típico: contar dos veces la intersección." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Razonamiento con proporciones",
          d: "Resolver problemas usando proporcionalidad y regla de tres razonada. Error típico: no reconocer si es directa o inversa." },
        { t: "Conteo y combinatoria básica",
          d: "Principio de multiplicación, permutaciones y combinaciones sencillas; contar sin repetir ni saltar. Error típico: contar desordenado." },
        { t: "Problemas de ingenio",
          d: "Acertijos de lógica (verdades/mentiras, ubicación, deducción). OJO: exigen UNA sola solución que cumpla TODAS las pistas. Error típico: aceptar una respuesta que no verifica todas las condiciones." },
        { t: "Resolución de problemas de varios pasos",
          d: "Descomponer un problema grande en pasos, resolver por partes y unir; comprobar. Error típico: perder un paso intermedio." },
      ]},
    ]},
    { id: 100, materia: "Lengua y Literatura", nombre_corto: "LENGUA Y LIT 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La comunicación y sus elementos",
          d: "Emisor, receptor, mensaje, código, canal y contexto; funciones del lenguaje (idea inicial). Error típico: confundir código con canal." },
        { t: "Comprensión lectora",
          d: "Idea principal, inferencias, propósito del autor y vocabulario por contexto en textos más largos que en primaria. Error típico: responder sin volver al texto." },
        { t: "El sustantivo, el adjetivo y el artículo",
          d: "Repaso con más profundidad: clases de sustantivo, grados del adjetivo, concordancia. Error típico: fallar concordancia en frases largas." },
        { t: "Acentuación: reglas generales",
          d: "Agudas, graves, esdrújulas y sobresdrújulas; tilde diacrítica básica (tú/tu, él/el, más/mas). Error típico: no aplicar la regla y guiarse por el sonido." },
        { t: "Género narrativo: el cuento",
          d: "Estructura, narrador (1ª/3ª persona), personajes y ambiente; analizar un cuento. Error típico: confundir autor con narrador." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El verbo y sus conjugaciones",
          d: "Modos y tiempos verbales; conjugaciones regulares y algunas irregulares; coherencia temporal. Error típico: mezclar tiempos en un mismo texto." },
        { t: "La oración: sujeto y predicado",
          d: "Núcleos del sujeto y del predicado; oración simple; complementos (idea básica). Error típico: confundir el núcleo con otra palabra." },
        { t: "Sinónimos, antónimos y homónimos",
          d: "Ampliar vocabulario; homónimos (vino/vino) y su distinción por contexto. Error típico: confundir homónimo con sinónimo." },
        { t: "El texto expositivo",
          d: "Estructura (introducción, desarrollo, conclusión) y lenguaje objetivo; para informar/explicar. Error típico: opinar en un texto que debe ser objetivo." },
        { t: "Género lírico: el poema y las figuras literarias",
          d: "Verso, estrofa, rima; figuras (símil, metáfora, personificación). Error típico: confundir símil (con 'como') y metáfora." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Uso de conectores",
          d: "Conectores de adición, causa, consecuencia, contraste y orden para dar cohesión. Error típico: repetir 'y'/'entonces' y usar el conector equivocado." },
        { t: "El texto argumentativo",
          d: "Tesis, argumentos y conclusión; defender una postura con razones. Error típico: dar opinión sin argumentos que la sostengan." },
        { t: "Ortografía: b/v, g/j, h",
          d: "Reglas frecuentes y familias de palabras; casos que más fallan. Error típico: escribir de oído sin aplicar reglas." },
        { t: "El ensayo breve",
          d: "Estructura sencilla del ensayo; introducir tema, desarrollar ideas propias y cerrar. Error típico: no delimitar el tema." },
        { t: "Literatura venezolana e hispanoamericana",
          d: "Autores y obras representativas; contexto básico. Error típico: memorizar títulos sin relacionarlos con su época/autor." },
      ]},
    ]},
    { id: 96, materia: "Física", nombre_corto: "FÍSICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La física y la medición",
          d: "Qué estudia la física; magnitud física; medir es comparar con una unidad; cifras y precisión (idea básica). Error típico: dar un número sin su unidad." },
        { t: "Magnitudes y unidades del Sistema Internacional",
          d: "Magnitudes fundamentales (longitud-m, masa-kg, tiempo-s) y derivadas; conversión de unidades. Error típico: sumar cantidades con distinta unidad sin convertir." },
        { t: "Notación científica",
          d: "Escribir números muy grandes/pequeños como a×10ⁿ; multiplicar y dividir potencias de 10. Error típico: contar mal los lugares de la coma y el signo del exponente." },
        { t: "Instrumentos de medición",
          d: "Regla, balanza, cronómetro, cilindro graduado; qué mide cada uno y cómo leerlo. Error típico: mala lectura de la escala (paralaje)." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El movimiento: posición, distancia y desplazamiento",
          d: "Sistema de referencia; distancia (recorrido total) vs desplazamiento (con dirección). Error típico: usarlos como sinónimos." },
        { t: "Rapidez y velocidad",
          d: "Rapidez = distancia/tiempo; velocidad incluye dirección; unidades (m/s, km/h) y su conversión. Error típico: confundir rapidez con velocidad y fallar la conversión km/h↔m/s." },
        { t: "Movimiento rectilíneo uniforme",
          d: "MRU: velocidad constante; fórmula d=v·t y despejes; gráfico posición-tiempo. Error típico: no despejar bien t o v de d=v·t." },
        { t: "Las fuerzas y sus efectos",
          d: "Fuerza como empujar/halar; efectos (deformar, mover, frenar); fuerzas equilibradas y no equilibradas. Error típico: creer que sin movimiento no hay fuerzas." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Trabajo, energía y potencia",
          d: "Trabajo = fuerza×distancia (idea básica); energía como capacidad de hacer trabajo; potencia como rapidez del trabajo. Error típico: llamar 'trabajo' a sostener algo sin desplazarlo." },
        { t: "Formas de energía y su transformación",
          d: "Cinética, potencial, térmica, eléctrica; conservación y transformación de la energía. Error típico: pensar que la energía se crea o desaparece." },
        { t: "El calor y la temperatura",
          d: "Diferencia entre calor (energía que se transfiere) y temperatura (nivel térmico); escalas; dilatación. Error típico: usar calor y temperatura como lo mismo." },
        { t: "Máquinas simples",
          d: "Palanca, polea, plano inclinado; ventaja mecánica (idea de que facilitan el trabajo). Error típico: creer que 'ahorran' energía en vez de facilitar la fuerza." },
      ]},
    ]},
    { id: 106, materia: "Química", nombre_corto: "QUÍMICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La química y la materia",
          d: "Qué estudia la química; materia como todo lo que tiene masa y ocupa espacio; masa vs peso. Error típico: confundir masa con peso." },
        { t: "Propiedades de la materia",
          d: "Propiedades generales (masa, volumen) y específicas (densidad, punto de fusión); físicas vs químicas. Error típico: clasificar mal una propiedad." },
        { t: "Estados de la materia y sus cambios",
          d: "Sólido, líquido, gas (y plasma); cambios de estado y el papel de la energía; teoría cinética (partículas). Error típico: nombrar mal el cambio (sublimación vs evaporación)." },
        { t: "Sustancias puras y mezclas",
          d: "Elemento, compuesto; mezcla homogénea y heterogénea; ejemplos. Error típico: llamar compuesto a una mezcla." },
        { t: "Métodos de separación de mezclas",
          d: "Filtración, decantación, evaporación, destilación, imantación, tamizado; elegir según la mezcla. Error típico: escoger un método que no aplica a esa mezcla." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "El átomo y su estructura",
          d: "Protones, neutrones y electrones; núcleo y corteza; número atómico y de masa (idea básica). Error típico: ubicar los electrones en el núcleo." },
        { t: "Elementos y la tabla periódica",
          d: "Organización en grupos y períodos; metales y no metales; leer una casilla. Error típico: confundir número atómico con masa." },
        { t: "Símbolos químicos",
          d: "Símbolos de elementos comunes (H, O, C, Na, Cl…) y su lectura. Error típico: mayúsculas/minúsculas (Co ≠ CO)." },
        { t: "Moléculas y compuestos",
          d: "Molécula como unión de átomos; fórmula química e interpretación (H₂O, CO₂). Error típico: leer mal los subíndices." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Enlaces químicos (idea básica)",
          d: "Por qué se unen los átomos; enlace iónico vs covalente en idea sencilla. Error típico: confundir los dos tipos de enlace." },
        { t: "Reacciones químicas",
          d: "Reactivos y productos; señales de una reacción (gas, color, calor); idea de conservación de la masa. Error típico: creer que aparece o desaparece materia." },
        { t: "El agua y sus propiedades",
          d: "Fórmula, propiedades y su importancia; el agua como disolvente. Error típico: no relacionar propiedades con usos." },
        { t: "La química en la vida diaria",
          d: "Química en alimentos, limpieza y medicinas; seguridad básica. Error típico: ver la química como algo ajeno a lo cotidiano." },
      ]},
    ]},
    { id: 94, materia: "Biología, Ambiente y Tecnología", nombre_corto: "BIOLOGÍA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La biología y los seres vivos",
          d: "Qué estudia la biología; características de los seres vivos (nacen, crecen, se reproducen, mueren, responden). Error típico: no distinguir vivo de no vivo en casos límite." },
        { t: "La célula: estructura y funciones",
          d: "Membrana, citoplasma, núcleo y organelos principales; célula animal vs vegetal. Error típico: confundir organelos y sus funciones." },
        { t: "Células procariotas y eucariotas",
          d: "Diferencia clave: con o sin núcleo definido; ejemplos (bacteria vs célula humana). Error típico: creer que procariota = 'pequeña' sin más." },
        { t: "Niveles de organización de la vida",
          d: "De célula a tejido, órgano, sistema, organismo… hasta ecosistema. Error típico: desordenar los niveles." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Clasificación de los seres vivos: los reinos",
          d: "Los reinos y criterios de clasificación; ejemplos de cada uno. Error típico: clasificar por apariencia y no por características." },
        { t: "Funciones vitales: nutrición, relación y reproducción",
          d: "Las tres funciones y cómo las cumplen distintos seres vivos. Error típico: reducir 'nutrición' a 'comer'." },
        { t: "La nutrición en plantas y animales",
          d: "Autótrofos vs heterótrofos; digestión básica; fotosíntesis como nutrición vegetal. Error típico: pensar que la planta se nutre del suelo." },
        { t: "Fotosíntesis y respiración",
          d: "Fotosíntesis (fabrica alimento con luz, libera O₂) y respiración celular (libera energía, usa O₂); son complementarias. Error típico: creer que las plantas no respiran." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Ecosistemas y cadenas alimentarias",
          d: "Productores, consumidores y descomponedores; flujo de energía; redes tróficas. Error típico: invertir el sentido de la cadena." },
        { t: "Biodiversidad de Venezuela",
          d: "Riqueza de especies y ecosistemas venezolanos; especies endémicas. Error típico: no relacionar biodiversidad con conservación." },
        { t: "El ambiente y su conservación",
          d: "Problemas ambientales y acciones de cuidado; desarrollo sostenible (idea básica). Error típico: soluciones vagas sin acción concreta." },
        { t: "Ciencia, tecnología y ambiente",
          d: "Cómo la tecnología impacta el ambiente (positiva y negativamente). Error típico: ver la tecnología solo como buena o solo como mala." },
      ]},
    ]},
    { id: 97, materia: "Geografía, Historia y Ciudadanía", nombre_corto: "GHC 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "El espacio geográfico",
          d: "Espacio geográfico como resultado de la relación sociedad-naturaleza; elementos naturales y humanos. Error típico: reducir geografía a memorizar mapas." },
        { t: "El universo, la Tierra y sus movimientos",
          d: "Rotación (día/noche) y traslación (estaciones); el sistema solar. Error típico: intercambiar los efectos de rotación y traslación." },
        { t: "Coordenadas geográficas",
          d: "Latitud y longitud; paralelos y meridianos; ubicar un punto. Error típico: confundir latitud con longitud." },
        { t: "Continentes y océanos",
          d: "Ubicación y rasgos generales; división política básica. Error típico: confundir continente con país." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Geografía de Venezuela: relieve, clima e hidrografía",
          d: "Grandes conjuntos de relieve, climas y ríos/cuencas principales. Error típico: mezclar relieve con clima." },
        { t: "Regiones naturales de Venezuela",
          d: "Regiones y sus características (recursos, actividades). Error típico: no ubicar cada región." },
        { t: "Población y poblamiento",
          d: "Distribución de la población, migración, urbano/rural. Error típico: confundir población con poblamiento." },
        { t: "Pueblos originarios y primeras civilizaciones",
          d: "Pueblos indígenas de Venezuela y aportes; primeras civilizaciones (idea general). Error típico: verlos solo 'del pasado'." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Descubrimiento y colonización de América",
          d: "Llegada europea, conquista y colonia; consecuencias (idea crítica básica). Error típico: relato de una sola cara." },
        { t: "La independencia de Venezuela",
          d: "Proceso, próceres y fechas clave; causas y consecuencias. Error típico: memorizar fechas sin causas." },
        { t: "Ciudadanía: derechos y deberes",
          d: "Derechos y deberes; participación y convivencia. Error típico: reclamar derechos sin deberes." },
        { t: "La Constitución y la convivencia",
          d: "Qué es la Constitución y su papel en las normas y la convivencia. Error típico: no relacionarla con la vida diaria." },
      ]},
    ]},
    { id: 99, materia: "Inglés", nombre_corto: "INGLÉS 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Verb to be and personal information",
          d: "am/is/are en afirmativo/negativo/pregunta; dar información personal. Error típico: omitir el verbo to be." },
        { t: "Subject pronouns",
          d: "I, you, he, she, it, we, they y concordancia con to be. Error típico: usar he/she para cosas." },
        { t: "Numbers, dates and the alphabet",
          d: "Números, fechas, deletreo; preguntar/decir la fecha. Error típico: orden de la fecha en inglés." },
        { t: "Countries and nationalities",
          d: "Países y nacionalidades; where are you from. Error típico: confundir país con nacionalidad." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Present simple and daily routines",
          d: "Rutinas; afirmativo/negativo/pregunta con do/does; la -s de 3ª persona. Error típico: 'he don't' y olvidar la -s." },
        { t: "Adverbs of frequency",
          d: "always, usually, sometimes, never; su posición en la oración. Error típico: colocarlos al final." },
        { t: "Family and jobs",
          d: "Vocabulario de familia y oficios; describir con present simple. Error típico: vocabulario mal ubicado en la frase." },
        { t: "There is / there are",
          d: "Existencia en singular/plural; some/any. Error típico: there is con plurales." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Present continuous",
          d: "am/is/are + verbo-ing para acciones en curso; contraste con present simple. Error típico: usar continuous para rutinas." },
        { t: "Can (ability)",
          d: "can/can't para habilidad; preguntas. Error típico: agregar 's' o 'to' después de can." },
        { t: "Prepositions of time and place",
          d: "in/on/at para tiempo y lugar. Error típico: elegir la preposición equivocada." },
        { t: "Describing people and places",
          d: "Adjetivos y su orden; describir personas y lugares. Error típico: poner el adjetivo después del sustantivo (como en español)." },
      ]},
    ]},
    { id: 98, materia: "Informática", nombre_corto: "INFORMÁTICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "El computador: hardware y software", d: "Componentes y tipos de software (sistema y aplicación). Error típico: confundir hardware con software." },
        { t: "Sistemas operativos", d: "Función del SO; escritorio, ventanas, gestión básica. Error típico: creer que el SO es 'la pantalla'." },
        { t: "Gestión de archivos y carpetas", d: "Crear, mover, copiar, renombrar; rutas y extensiones. Error típico: perder archivos por no saber la ruta." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Procesador de texto", d: "Formato, párrafos, listas, insertar imágenes; guardar en formatos. Error típico: dar formato manual en vez de estilos." },
        { t: "Hoja de cálculo básica", d: "Celdas, filas, columnas; fórmulas simples (=SUMA), gráficos. Error típico: no empezar la fórmula con '='." },
        { t: "Presentaciones digitales", d: "Diapositivas con jerarquía visual; poco texto, buenas imágenes. Error típico: saturar de texto." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Internet y buscadores", d: "Buscar con criterio y evaluar fuentes; palabras clave. Error típico: creer todo lo que aparece primero." },
        { t: "Seguridad y ciudadanía digital", d: "Contraseñas, privacidad, huella digital, respeto en línea. Error típico: compartir datos personales." },
        { t: "Introducción a la programación", d: "Algoritmo, secuencia, condición y repetición (idea/bloques). Error típico: pasos ambiguos o incompletos." },
      ]},
    ]},
    { id: 176, materia: "Electrónica", nombre_corto: "ELECTRÓNICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La electricidad: conceptos básicos", d: "Carga eléctrica, conductores y aislantes; electricidad estática vs corriente. Error típico: confundir conductor con aislante." },
        { t: "Corriente, voltaje y resistencia", d: "Qué es cada uno con analogía del agua (corriente=flujo, voltaje=presión, resistencia=estrechez); unidades A, V, Ω. Error típico: mezclar los tres conceptos." },
        { t: "Circuitos eléctricos simples", d: "Fuente, conductor, carga e interruptor; circuito abierto vs cerrado. Error típico: creer que enciende con el circuito abierto." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Componentes electrónicos: resistencias, LED, interruptores", d: "Qué hace cada componente y su símbolo; polaridad del LED. Error típico: conectar el LED al revés." },
        { t: "La ley de Ohm", d: "V = I·R y sus despejes; calcular la magnitud faltante; unidades. Error típico: despejar mal o mezclar unidades." },
        { t: "Instrumentos de medición", d: "Multímetro: medir voltaje, corriente y resistencia; conexión correcta. Error típico: medir corriente en paralelo." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Circuitos en serie y en paralelo", d: "Diferencias, cómo se reparten voltaje/corriente; qué pasa si falla un elemento. Error típico: confundir el comportamiento de serie vs paralelo." },
        { t: "Montaje de circuitos básicos", d: "Armar en protoboard siguiendo un esquema; verificar conexiones. Error típico: mala lectura del esquema." },
        { t: "Proyecto de electrónica", d: "Diseñar y montar un circuito con propósito (ej. semáforo LED). Error típico: no planificar antes de montar." },
      ]},
    ]},
    { id: 108, materia: "Robótica", nombre_corto: "ROBÓTICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Introducción a la robótica", d: "Qué es un robot y sus aplicaciones; sistemas de control (idea). Error típico: llamar robot a cualquier máquina." },
        { t: "Partes de un robot", d: "Estructura, sensores, controlador y actuadores. Error típico: confundir sensor con actuador." },
        { t: "Sensores y actuadores", d: "El sensor percibe, el actuador ejecuta; ejemplos reales. Error típico: intercambiar sus roles." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Algoritmos y programación por bloques", d: "Diseñar un algoritmo y traducirlo a bloques; probar y depurar. Error típico: no probar por pasos." },
        { t: "Control de motores", d: "Encender, controlar velocidad y giro; tiempos. Error típico: no calibrar tiempos/distancias." },
        { t: "Lógica de programación", d: "Secuencia, condiciones (si...entonces) y bucles (repetir). Error típico: condición mal planteada." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Diseño y armado de un robot", d: "De la idea al prototipo; estructura estable. Error típico: montar sin plan." },
        { t: "Programación de tareas", d: "Programar el robot para una tarea concreta paso a paso. Error típico: instrucciones incompletas." },
        { t: "Proyecto final de robótica", d: "Integrar sensores, motores y lógica en un reto. Error típico: no dividir el reto en partes." },
      ]},
    ]},
    { id: 104, materia: "Metodología", nombre_corto: "METODOLOGÍA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "El conocimiento y la ciencia", d: "Conocimiento cotidiano vs científico; qué hace 'científico' a un saber. Error típico: creer que ciencia es solo laboratorio." },
        { t: "El método científico", d: "Pasos: observación, pregunta, hipótesis, experimentación, análisis y conclusión. CLAVE en bachillerato. Error típico: desordenar los pasos o saltar la hipótesis." },
        { t: "Observación y planteamiento de problemas", d: "Observar con detalle y convertir una duda en una pregunta investigable. Error típico: preguntas demasiado amplias o no comprobables." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Fuentes de información", d: "Fuentes primarias y secundarias; evaluar confiabilidad. Error típico: usar fuentes poco fiables." },
        { t: "La investigación documental", d: "Buscar, seleccionar y organizar información sobre un tema. Error típico: copiar sin procesar." },
        { t: "Fichas y citas", d: "Registrar datos en fichas y citar para no plagiar. Error típico: no citar la fuente." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "El proyecto de investigación", d: "Partes de un proyecto: tema, objetivos, justificación. Error típico: objetivos vagos." },
        { t: "Recolección de datos", d: "Encuesta, entrevista y observación; instrumentos simples. Error típico: preguntas mal formuladas." },
        { t: "Presentación de resultados", d: "Organizar y comunicar resultados con claridad (tablas, gráficos). Error típico: presentar datos sin interpretarlos." },
      ]},
    ]},
    { id: 105, materia: "Orientación y Convivencia", nombre_corto: "ORIENTACIÓN 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Autoconocimiento y autoestima", d: "Conocer fortalezas y áreas de mejora; autoestima sana. Error típico: confundir autoestima con creerse superior." },
        { t: "Cambios en la adolescencia", d: "Cambios físicos y emocionales; manejarlos con información. Error típico: normalizar mitos." },
        { t: "Hábitos de estudio", d: "Organización del tiempo, lugar de estudio, técnicas (resumen, repaso espaciado). CLAVE para el salto a bachillerato. Error típico: estudiar todo a última hora." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Convivencia y valores", d: "Respeto, responsabilidad y tolerancia en el grupo. Error típico: valores en teoría, no en actos." },
        { t: "Comunicación asertiva", d: "Expresar lo que se piensa/siente con respeto, sin agredir ni callar. Error típico: confundir asertividad con agresividad." },
        { t: "Resolución de conflictos", d: "Escuchar, dialogar y negociar acuerdos. Error típico: evitar el conflicto en vez de resolverlo." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Proyecto de vida", d: "Metas a corto y largo plazo; pasos para lograrlas. Error típico: metas sin plan." },
        { t: "Trabajo en equipo", d: "Roles, responsabilidad compartida y aporte de cada uno. Error típico: dependencia de una sola persona." },
        { t: "Prevención y salud integral", d: "Cuidado físico, emocional y social; decisiones responsables. Error típico: ver la salud solo como lo físico." },
      ]},
    ]},
    { id: 101, materia: "Liderazgo Comunicacional", nombre_corto: "LID COMUNIC 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La comunicación efectiva", d: "Claridad, escucha y retroalimentación; barreras de la comunicación. Error típico: hablar sin verificar que entendieron." },
        { t: "Expresión oral y corporal", d: "Voz, postura y gestos que acompañan el mensaje. Error típico: lenguaje corporal que contradice las palabras." },
        { t: "Escucha activa", d: "Atender, parafrasear y preguntar. Error típico: interrumpir." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Liderazgo y trabajo en equipo", d: "Estilos de liderazgo y colaboración. Error típico: confundir liderar con imponer." },
        { t: "Oratoria y debate", d: "Argumentar, refutar con respeto y estructurar un discurso. Error típico: atacar a la persona y no al argumento." },
        { t: "Manejo de conflictos", d: "Mediación y acuerdos ganar-ganar. Error típico: buscar culpables en vez de soluciones." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Proyectos comunitarios", d: "Detectar necesidades y organizar una acción; roles y metas. Error típico: planificar sin ejecutar." },
        { t: "Vocería y participación", d: "Representar al grupo y participar con responsabilidad. Error típico: hablar sin consultar al grupo." },
        { t: "Comunicación y redes", d: "Uso responsable de redes para comunicar; ciudadanía digital. Error típico: difundir sin verificar." },
      ]},
    ]},
    { id: 107, materia: "Religión", nombre_corto: "RELIGIÓN 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "La fe y la persona", d: "La dimensión espiritual del ser humano; fe y sentido. Error típico: reducir la fe a ritos." },
        { t: "La Biblia: Antiguo y Nuevo Testamento", d: "Estructura y contenido general de ambos testamentos. Error típico: mezclar los dos." },
        { t: "Valores cristianos", d: "Amor, justicia, perdón y solidaridad en la vida. Error típico: valores sin práctica." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Jesús y su mensaje", d: "Vida y enseñanzas centrales de Jesús. Error típico: hechos sin mensaje." },
        { t: "Las parábolas", d: "Significado de las parábolas principales. Error típico: interpretación literal." },
        { t: "La solidaridad y el servicio", d: "Servir a los demás con acciones concretas. Error típico: servir por interés." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "La Iglesia y la comunidad", d: "La comunidad de fe y su papel social. Error típico: verla solo como edificio." },
        { t: "Ética y moral", d: "Distinción básica; decisiones según valores. Error típico: confundir ética con reglas impuestas." },
        { t: "Proyecto de vida cristiano", d: "Metas de vida guiadas por valores. Error típico: metas sin coherencia con los valores." },
      ]},
    ]},
    { id: 95, materia: "Educación Física", nombre_corto: "EDUC FÍSICA 1A", grupos: [
      { lapso: "Primer lapso", temas: [
        { t: "Capacidades físicas y calentamiento", d: "Fuerza, resistencia, velocidad, flexibilidad; calentar y enfriar. Error típico: no calentar." },
        { t: "Acondicionamiento físico", d: "Rutinas seguras y progresivas; frecuencia cardíaca (idea). Error típico: sobreesfuerzo sin progresión." },
        { t: "Atletismo", d: "Carreras, saltos y lanzamientos; técnica básica. Error típico: mala técnica de respiración/zancada." },
      ]},
      { lapso: "Segundo lapso", temas: [
        { t: "Deportes colectivos: voleibol, baloncesto y fútbol", d: "Fundamentos y reglas básicas de cada uno. Error típico: desconocer faltas comunes." },
        { t: "Reglas y técnicas", d: "Reglamento básico y gestos técnicos. Error típico: aplicar reglas de un deporte a otro." },
        { t: "Trabajo en equipo", d: "Cooperación, roles y juego limpio. Error típico: juego individualista." },
      ]},
      { lapso: "Tercer lapso", temas: [
        { t: "Gimnasia y expresión corporal", d: "Equilibrio, coordinación y expresión. Error típico: rigidez y falta de control." },
        { t: "Salud, nutrición y actividad física", d: "Relación entre ejercicio, alimentación y descanso. Error típico: descuidar hidratación/descanso." },
        { t: "Recreación y juegos tradicionales", d: "Juegos venezolanos y su valor. Error típico: no respetar las reglas del juego." },
      ]},
    ]},
    { id: 971, materia: "Puente al Bachillerato", nombre_corto: "PUENTE 1A", grupos: [
      { lapso: "Cierra el salto de 6to a 1er año", temas: [
        { t: "Números negativos: la regla de signos con confianza",
          d: "El tema que más frena al que llega de primaria. Sumar y restar en la recta (deber/tener), multiplicar y dividir con la regla de signos (− por − = +), restar un negativo (a−(−b)=a+b). Error típico: '−3−5' y '−2×−4'. Practicar mucho con contextos (temperaturas, deudas, ascensor)." },
        { t: "De la aritmética al álgebra: qué significa la letra",
          d: "Entender que una letra representa un número desconocido o variable; término, coeficiente, términos semejantes; evaluar una expresión sustituyendo. Es el corazón del salto a bachillerato. Error típico: creer que 'x' es una unidad o sumar 3x+2 como 5x." },
        { t: "Despejar: resolver ecuaciones de primer grado paso a paso",
          d: "Resolver x+a=b, ax=b y ax+b=c; la idea de 'balanza' (lo que hago de un lado lo hago del otro) y 'lo que pasa al otro lado cambia de operación'; comprobar sustituyendo. Error típico: cambiar mal el signo/operación al pasar términos y no verificar." },
        { t: "Jerarquía de operaciones y paréntesis (PEMDAS)",
          d: "Orden correcto: paréntesis, potencias, ×/÷, +/−; operaciones combinadas con negativos. Base de todo el cálculo de bachillerato. Error típico: resolver de izquierda a derecha ignorando la jerarquía." },
        { t: "Fracciones, decimales y porcentajes son lo mismo",
          d: "Convertir con soltura entre fracción, decimal y porcentaje (1/4=0,25=25%); operar con fracciones incluyendo signo; usarlas en problemas reales. Error típico: tratarlos como temas separados y perder el signo." },
        { t: "El método científico y los hábitos de estudio",
          d: "En bachillerato aparecen Física, Química y Biología con enfoque científico: observar, plantear hipótesis, experimentar y concluir. Y estudiar cambia: organizar el tiempo, tomar apuntes, resumir y repasar espaciado (no todo la víspera). Error típico: memorizar sin entender y dejar todo para el final." },
      ]},
    ]},
  ],
};
